name: democritus
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.11.0=pyhd3eb1b0_1
  - astor=0.8.1=py37hecd8cb5_0
  - blas=1.0=mkl
  - bzip2=1.0.8=hc929b4f_4
  - c-ares=1.17.1=h9ed2024_0
  - ca-certificates=2020.12.5=h033912b_0
  - cairo=1.16.0=h4ec454a_1007
  - certifi=2020.12.5=py37hf985489_1
  - click=7.1.2=pyhd3eb1b0_0
  - coverage=5.5=py37h9ed2024_2
  - cython=0.29.22=py37h23ab428_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - ffmpeg=4.3.1=hb787a4c_2
  - flask=1.1.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=hd23ceaa_1004
  - freetype=2.10.4=h4cff582_1
  - gast=0.2.2=py37_0
  - gettext=0.19.8.1=h7937167_1005
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h2e338ed_1001
  - grpcio=1.36.1=py37h97de6d8_1
  - h5py=2.10.0=py37h0601b69_1
  - harfbuzz=2.7.4=hf28d55f_0
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2019.4=233
  - itsdangerous=1.1.0=py37_0
  - jasper=1.900.1=h636a363_1006
  - jellyfish=0.8.2=py37hf967b71_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=hbcb3906_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.17.2=h60d9502_0
  - lame=3.100=h35c211d_1001
  - libblas=3.9.0=1_h508aa58_netlib
  - libcblas=3.9.0=3_h3cd88c1_netlib
  - libcurl=7.75.0=h8ef9fac_0
  - libcxx=11.1.0=habf9029_0
  - libedit=3.1.20191231=h1de35cc_1
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_19
  - libgfortran5=9.3.0=h6c81a4c_19
  - libglib=2.66.7=hd556434_1
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=3_h3cd88c1_netlib
  - liblapacke=3.9.0=3_h3cd88c1_netlib
  - libnghttp2=1.43.0=h07e645a_0
  - libopencv=4.5.1=py37h2dd4c96_0
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.14.0=h2842e9f_0
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.2.0=h355d032_0
  - libwebp-base=1.2.0=hbcf498f_0
  - libxml2=2.9.10=h802ca4f_3
  - llvm-openmp=11.0.1=h7c73e74_0
  - lz4-c=1.9.3=h046ec9c_0
  - markdown=3.3.4=py37hecd8cb5_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37ha059aab_0
  - mkl_random=1.1.1=py37h959d312_0
  - ncurses=6.2=h0a44026_1
  - nettle=3.6=hedd7734_0
  - networkx=2.5=py_0
  - nltk=3.5=py_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - opencv=4.5.1=py37hf985489_0
  - openh264=2.1.1=hfd3ada9_0
  - openssl=1.1.1j=hbcf498f_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.2.3=py37hb2f4e1b_0
  - pcre=8.44=hb1e8313_0
  - pip=21.0.1=py37hecd8cb5_0
  - pixman=0.40.0=hbcb3906_0
  - protobuf=3.14.0=py37h23ab428_1
  - py-opencv=4.5.1=py37he01cfaa_0
  - python=3.7.10=h88f2d9e_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h9ed2024_1
  - readline=8.1=h9ed2024_0
  - regex=2020.11.13=py37h9ed2024_0
  - scipy=1.6.0=py37hc22aa43_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.15.0=py37hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37hecd8cb5_1
  - tk=8.6.10=hb0a8c7a_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h1de35cc_1
  - x264=1!161.3030=h35c211d_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h582d3a0_0
  - pip:
    - gunicorn==20.0.4
